data:
  name: [None, "Kitti"]
  # split: [None, "eval_visualize"]     # for qualitative output as in the paper
  split: [None, "trainval"]     # for quantitative output
  tr_crop_size: [352, 704]
  te_crop_size: [352, 704]
  norm_type: "imagenet-norm"