data:
  path: '/scratch/hpeng_root/hpeng1/minghanz/kitti_data/'
snap:
  # path: "/data/snap_dir/monodepth"
  # path: "./snap_dir/monodepth"
  path: "/scratch/hpeng_root/hpeng1/minghanz/tmp/DORN_pytorch/snap_dir/monodepth"

